// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.googlecode.protobuf.socketrpc.helloworld;

public final class HelloWorld {
  private HelloWorld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HelloRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string my_name = 2;
    /**
     * <code>required string my_name = 2;</code>
     */
    boolean hasMyName();
    /**
     * <code>required string my_name = 2;</code>
     */
    java.lang.String getMyName();
    /**
     * <code>required string my_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getMyNameBytes();
  }
  /**
   * Protobuf type {@code protobuf.socketrpc.HelloRequest}
   */
  public static final class HelloRequest extends
      com.google.protobuf.GeneratedMessage
      implements HelloRequestOrBuilder {
    // Use HelloRequest.newBuilder() to construct.
    private HelloRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HelloRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HelloRequest defaultInstance;
    public static HelloRequest getDefaultInstance() {
      return defaultInstance;
    }

    public HelloRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HelloRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              myName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest.class, com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<HelloRequest> PARSER =
        new com.google.protobuf.AbstractParser<HelloRequest>() {
      public HelloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HelloRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string my_name = 2;
    public static final int MY_NAME_FIELD_NUMBER = 2;
    private java.lang.Object myName_;
    /**
     * <code>required string my_name = 2;</code>
     */
    public boolean hasMyName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string my_name = 2;</code>
     */
    public java.lang.String getMyName() {
      java.lang.Object ref = myName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          myName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string my_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMyNameBytes() {
      java.lang.Object ref = myName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        myName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      myName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMyName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getMyNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMyNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.socketrpc.HelloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest.class, com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest.Builder.class);
      }

      // Construct using com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        myName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloRequest_descriptor;
      }

      public com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest getDefaultInstanceForType() {
        return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest.getDefaultInstance();
      }

      public com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest build() {
        com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest buildPartial() {
        com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest result = new com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.myName_ = myName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest) {
          return mergeFrom((com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest other) {
        if (other == com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest.getDefaultInstance()) return this;
        if (other.hasMyName()) {
          bitField0_ |= 0x00000001;
          myName_ = other.myName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMyName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string my_name = 2;
      private java.lang.Object myName_ = "";
      /**
       * <code>required string my_name = 2;</code>
       */
      public boolean hasMyName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string my_name = 2;</code>
       */
      public java.lang.String getMyName() {
        java.lang.Object ref = myName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          myName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string my_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMyNameBytes() {
        java.lang.Object ref = myName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          myName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string my_name = 2;</code>
       */
      public Builder setMyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        myName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string my_name = 2;</code>
       */
      public Builder clearMyName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        myName_ = getDefaultInstance().getMyName();
        onChanged();
        return this;
      }
      /**
       * <code>required string my_name = 2;</code>
       */
      public Builder setMyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        myName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.socketrpc.HelloRequest)
    }

    static {
      defaultInstance = new HelloRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.socketrpc.HelloRequest)
  }

  public interface HelloResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string hello_world = 1;
    /**
     * <code>required string hello_world = 1;</code>
     */
    boolean hasHelloWorld();
    /**
     * <code>required string hello_world = 1;</code>
     */
    java.lang.String getHelloWorld();
    /**
     * <code>required string hello_world = 1;</code>
     */
    com.google.protobuf.ByteString
        getHelloWorldBytes();
  }
  /**
   * Protobuf type {@code protobuf.socketrpc.HelloResponse}
   */
  public static final class HelloResponse extends
      com.google.protobuf.GeneratedMessage
      implements HelloResponseOrBuilder {
    // Use HelloResponse.newBuilder() to construct.
    private HelloResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HelloResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HelloResponse defaultInstance;
    public static HelloResponse getDefaultInstance() {
      return defaultInstance;
    }

    public HelloResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HelloResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              helloWorld_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.class, com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<HelloResponse> PARSER =
        new com.google.protobuf.AbstractParser<HelloResponse>() {
      public HelloResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HelloResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string hello_world = 1;
    public static final int HELLO_WORLD_FIELD_NUMBER = 1;
    private java.lang.Object helloWorld_;
    /**
     * <code>required string hello_world = 1;</code>
     */
    public boolean hasHelloWorld() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string hello_world = 1;</code>
     */
    public java.lang.String getHelloWorld() {
      java.lang.Object ref = helloWorld_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          helloWorld_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hello_world = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHelloWorldBytes() {
      java.lang.Object ref = helloWorld_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        helloWorld_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      helloWorld_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHelloWorld()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHelloWorldBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHelloWorldBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.socketrpc.HelloResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.class, com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.Builder.class);
      }

      // Construct using com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        helloWorld_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.internal_static_protobuf_socketrpc_HelloResponse_descriptor;
      }

      public com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse getDefaultInstanceForType() {
        return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.getDefaultInstance();
      }

      public com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse build() {
        com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse buildPartial() {
        com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse result = new com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.helloWorld_ = helloWorld_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse) {
          return mergeFrom((com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse other) {
        if (other == com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.getDefaultInstance()) return this;
        if (other.hasHelloWorld()) {
          bitField0_ |= 0x00000001;
          helloWorld_ = other.helloWorld_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHelloWorld()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string hello_world = 1;
      private java.lang.Object helloWorld_ = "";
      /**
       * <code>required string hello_world = 1;</code>
       */
      public boolean hasHelloWorld() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string hello_world = 1;</code>
       */
      public java.lang.String getHelloWorld() {
        java.lang.Object ref = helloWorld_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          helloWorld_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hello_world = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHelloWorldBytes() {
        java.lang.Object ref = helloWorld_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          helloWorld_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hello_world = 1;</code>
       */
      public Builder setHelloWorld(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        helloWorld_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hello_world = 1;</code>
       */
      public Builder clearHelloWorld() {
        bitField0_ = (bitField0_ & ~0x00000001);
        helloWorld_ = getDefaultInstance().getHelloWorld();
        onChanged();
        return this;
      }
      /**
       * <code>required string hello_world = 1;</code>
       */
      public Builder setHelloWorldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        helloWorld_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.socketrpc.HelloResponse)
    }

    static {
      defaultInstance = new HelloResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.socketrpc.HelloResponse)
  }

  /**
   * Protobuf service {@code protobuf.socketrpc.HelloWorldService}
   */
  public static abstract class HelloWorldService
      implements com.google.protobuf.Service {
    protected HelloWorldService() {}

    public interface Interface {
      /**
       * <code>rpc HelloWorld(.protobuf.socketrpc.HelloRequest) returns (.protobuf.socketrpc.HelloResponse);</code>
       */
      public abstract void helloWorld(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest request,
          com.google.protobuf.RpcCallback<com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new HelloWorldService() {
        @java.lang.Override
        public  void helloWorld(
            com.google.protobuf.RpcController controller,
            com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest request,
            com.google.protobuf.RpcCallback<com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse> done) {
          impl.helloWorld(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.helloWorld(controller, (com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc HelloWorld(.protobuf.socketrpc.HelloRequest) returns (.protobuf.socketrpc.HelloResponse);</code>
     */
    public abstract void helloWorld(
        com.google.protobuf.RpcController controller,
        com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest request,
        com.google.protobuf.RpcCallback<com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.helloWorld(controller, (com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest)request,
            com.google.protobuf.RpcUtil.<com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloWorldService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void helloWorld(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest request,
          com.google.protobuf.RpcCallback<com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.class,
            com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse helloWorld(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse helloWorld(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.googlecode.protobuf.socketrpc.helloworld.HelloWorld.HelloResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:protobuf.socketrpc.HelloWorldService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_socketrpc_HelloRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_socketrpc_HelloRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_socketrpc_HelloResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_socketrpc_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021hello_world.proto\022\022protobuf.socketrpc\"" +
      "\037\n\014HelloRequest\022\017\n\007my_name\030\002 \002(\t\"$\n\rHell" +
      "oResponse\022\023\n\013hello_world\030\001 \002(\t2f\n\021HelloW" +
      "orldService\022Q\n\nHelloWorld\022 .protobuf.soc" +
      "ketrpc.HelloRequest\032!.protobuf.socketrpc" +
      ".HelloResponseB4\n,com.googlecode.protobu" +
      "f.socketrpc.helloworld\210\001\001\220\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_socketrpc_HelloRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_socketrpc_HelloRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_socketrpc_HelloRequest_descriptor,
              new java.lang.String[] { "MyName", });
          internal_static_protobuf_socketrpc_HelloResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_socketrpc_HelloResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_socketrpc_HelloResponse_descriptor,
              new java.lang.String[] { "HelloWorld", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
